### ISSUE TITLE
下载速度最高只能测到70M/S

### ISSUE THREAD

**Issue by Ke-Ze** [AiursoftWeb/Tracer#13]
clone源码release编译发布在iis上，配了内网域名和自签名证书，再无任何其他操作，在千兆内网环境下客户端的下载速度最高只能测到70M/S（一般达不到）平均在60左右，服务端占用带宽只有8.5mbps(较为稳定)，2个客户端连接时服务端带宽占用稳定为16mbps左右

**Comment by Anduin2017** [comment]
Might be a limitation from IIS itself. Suggest you try another OS or a web server like Nginx or CaddyV2.

If you insist to use IIS, please check the following steps:

Make sure that IIS doesn't have max bandwidth set to something wacky.

http://www.iis.net/configreference/system.applicationhost/sites/site/limits

You might want to experiment with:

* Disabling TCP Chimney Offload
* Disabling Receive Side Scaling
* Disabling Network Direct Memory Access

http://support.microsoft.com/kb/951037

**Comment by Anduin2017** [comment]
Fixed.

![image](https://github.com/user-attachments/assets/8b6c0026-37aa-4d2c-aff3-d692086fc375)
